# Generated by Django 2.2 on 2021-01-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='videoId',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='videolikes',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='videolikes',
            old_name='videoId',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='views',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='views',
            old_name='videoId',
            new_name='video',
        ),
    ]
